[package]
name = "crypto"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true

description = "Set of operation to handle: Key-generation, encryption and decryption"

[dependencies]
rsa.workspace = true
sha2.workspace = true
rand.workspace = true

